### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by Paoloc99** [bbaaii/DreamDiffusion#24]
Hi, I'm trying to run your implementation locally but I'm facing this issue during the fine-tuning phase:

`RuntimeError: CUDA out of memory. Tried to allocate 2.00 GiB (GPU 0; 8.00 GiB total capacity; 10.16 GiB already allocated; 0 bytes free; 13.00 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

Does anyone know how can I fix this? I have an RTX 3060 Ti 8GB, i5 11400, and 16GB RAM DDR4.
Thank you in advance for the help and good job with this project!!

**Comment by Cristian-Fioravanti** [comment]
i also have the same problem

**Comment by taziksh** [comment]
What's your batch size?

**Comment by Cristian-Fioravanti** [comment]
batch size = 4

**Comment by Paoloc99** [comment]
I have also tested with batch size 2 receiving the same error.
Can reducing image sizes help?

**Comment by taziksh** [comment]
1) Is this pre-training or finetuning?
2) How much VRAM is in your GPU?

**Comment by Paoloc99** [comment]
This happens during finetuning. My GPU is 8GB VRAM

**Comment by mahui-HUE** [comment]
> 我也有同样的问题，我是两张3090显卡，每张显存24G，设置了batch=2还是这个问题。

我解决了，设置batch为4，img_size=256，扩散模型本身的配置也改成img=256就可以双卡跑了。
